### PR TITLE
Corrects Ebony Pudding spell list

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

This PR corrects Ebony Puddings in ToAU to use proper spells.  Before they were linked to the beastmen BLM spell list, which allows them to cast improper spells.

Further research required to determine if this spell list is appropriate for all flans and/or if any additional spells need to be added.

### CODE REVIEW

**Comment by tankfest** [comment]
> 
> 
> Is the spell list about the same for all puddings of the same level range? We could maybe use the upper level value and make one list for puddings - I think the problem with the generic blm spell list was that it gave them access to a tier higher than it should have due to the lv, right?

That's what I suspected we could do... but we'd need data from other flan types to confirm.  I just help emulate retail, I don't delve into it myself ^.^

**Comment by TeoTwawki** [comment]
> 
> 
> > Is the spell list about the same for all puddings of the same level range? We could maybe use the upper level value and make one list for puddings - I think the problem with the generic blm spell list was that it gave them access to a tier higher than it should have due to the lv, right?
> 
> That's what I suspected we could do... but we'd need data from other flan types to confirm. I just help emulate retail, I don't delve into it myself ^.^

That is what the capture volunteers are there for Tank.

**Review by 59blargedy — COMMENTED** [review]
i am about 95% sure they also cast stun

**Comment by TeoTwawki** [comment]
They probably have drain if they have aspir.

**Comment by tankfest** [comment]
Drain/Stun added.

**Review by 59blargedy — APPROVED** [review]

**Pull request merged**
