### PR TITLE
if charming a player that may be charmed, or in ballista bind them

### PR DESCRIPTION
**Pull request by KnowOne134**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

tested with logging in 2 chars, having a mob charm 1 then using charm on the charmed char to give them a random bind effect for  to 5 seconds

### CODE REVIEW

**Comment by ibm2431** [comment]
> The following job abilities are altered: 
> [Charm, Gauge, and Tame have no effect whatsoever.](https://www.bg-wiki.com/bg/Category:Ballista)

Do we have a capture to confirm?

**Comment by KnowOne134** [comment]
I know I'll ballista to be 100% true. Atm this is a game crash if you try
it. Makes sense to me that you cant charm a charmed player to you either
will get a cannot do that on target or this

**Comment by ibm2431** [comment]
I will do my best to remember to test retail Charm Ballista behavior this period if someone else doesn't beat me to it.

**Review by ibm2431 — CHANGES_REQUESTED** [review]
We've talked on Discord, but I'm adding a "changes requested" note here so others know that retail does "no effect"~!

**Review by ibm2431 — APPROVED** [review]

**Pull request merged**
