### PR TITLE
Add a system message when using `!setGil` command

### PR DESCRIPTION
**Pull request by mrhappyasthma**
Small quality of life improvement when using the `!setGil` command.

Also a small whitespace adjustment to better match the rest of the file's style.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by TeoTwawki — COMMENTED** [review]
Think you meant “was set to” not “was to”

**Comment by TeoTwawki** [comment]
Wanna fix the indent/formatting while in this file to bring it up to contrib. guide spec? :)

**Comment by mrhappyasthma** [comment]
Good catch. fixed the typo.

The indentation looks accurate to me. Was there anything in particular you wanted to fix up?

**Comment by TeoTwawki** [comment]
I guess its github having mobile rendering issues. It looked like the indents were missing off the upper half of the file. Switch to “desktop node” on my phone and they look right..

**Comment by mrhappyasthma** [comment]
As far as I can tell, it's using 4x indentation everywhere.

**Comment by TeoTwawki** [comment]
Its github being a dumb git when viewed from ios embedded browser inside my email app

**Review by ibm2431 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
