### PR TITLE
Adjusted Switchstix Relic wait time to current retail

### PR DESCRIPTION
**Pull request by illzbee**
Adjusted Switchstix Relic wait time to current retail from JP (server) midnight to next game day

**_I affirm:_**
- [X] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [X] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by Kreidos** [comment]
Good fix! Thanks illzbee. 

It looks like an extra file might have come along for the ride though. :(

**Comment by illzbee** [comment]
> Good fix! Thanks illzbee.
> 
> It looks like an extra file might have come along for the ride though. :(

Deleted the extra file thanks :)

**Review by Kreidos — APPROVED** [review]
Yup! Looks good!

**Review by Kreidos — CHANGES_REQUESTED** [review]
One last thing though, I don't think getVanaMidnight() needs an argument. I don't see `day` defined here.

It won't hurt anything as it is, but it isn't needed. :)

**Review by Kreidos — APPROVED** [review]
Good stuff, thanks illzbee!

**Review by ibm2431 — APPROVED** [review]
Looks accurate, thanks illzbee (and Kreidos)!

(Merge button hitter: squash please~)

**Review by cocosolos — APPROVED** [review]

**Pull request merged**
