### PR TITLE
Prefill Trust and Intermediate ROE Records

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Need these for my trust branch - hitting level and speaking to ROE NPC when you have x sparks aren't implemented yet (I think?)

### CODE REVIEW

**Comment by Kreidos** [comment]
I might recommend leaving them commented out until they're actually completeable, as their presence in the table is what allows people to take them. And just removing the `--` in a Trust branch commit when you are ready for them should still avoid any possible conflict issues from `release` if others want to work on other parts of the file.

**Comment by zach2good** [comment]
Ah, I see what you mean!

**Review by Kreidos — APPROVED** [review]
I can't really argue with code that doesn't do anything! :man_shrugging: 
Table entries all look good.

**Review by ibm2431 — COMMENTED** [review]
`Allman Braces` 👀

**Comment by zach2good** [comment]
_Ooof_

At this point in `roe_records` life, changing the already consistent style to something else is too much of a pain in the ass. While I've personally seen the benefit of all this data being in a flexible lua table that we can refresh, I don't think it should _always_ be that way. Since it is a somewhat static (but large) set of data I'd like to one day see it plopped into the db. 

How that happens in the future is anyone's guess. Thats a problem for future developers.

**Comment by Kreidos** [comment]
if someone can offer of a way of storing something as highly varied as RoE record data in a db without it turning into a nightmare, I'm all ears. (Look at the magian table for just a tiny taste of that life.) Particularly records that don't behave like all the other records (take/deal damage, complete X mission, timed/scheduled 4-hour records, etc.) Plus the fact that records can have arbitrary number of requirements... Do we just make 6 requirement columns and hope that's enough? One row per requirement and have thousands of more rows? 

I also don't feel the overhead of using a Lua table is as high as may be indicated.

**Comment by Kreidos** [comment]
PS. use vim! I can fix the table pretty quick if it's that bothersome. I was under the impression that same-line open braces were pretty standard Lua style but I see that it's in the new style guide for Lua too.

**Pull request merged**
