### PR TITLE
Add optional nation param to getRank, Rank change NPCs to display target nation rank

### LINKED ISSUE #1351: Message from the NPC in charge of transfers in your country
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When you transfer, the NPC will tell you the RANK in the country you are transferring to.
However, the message displayed was the RANK of your current country before the transfer.
https://github.com/project-topaz/topaz/blob/cdf93c29cb9d3fd11a3e25ee572ef3ac2265ca0b/scripts/zones/Metalworks/npcs/Mythily.lua#L39

I think you can solve this problem if you have a function that allows you to get the RANK of any country.

### PR DESCRIPTION
**Pull request by rude-jerk**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Resolves #1351

### CODE REVIEW

**Comment by rude-jerk** [comment]
Resolves https://github.com/project-topaz/topaz/issues/1351

**Review by TeoTwawki — APPROVED** [review]
looks good to me and Ci says good :+1:

**Review by Kreidos — APPROVED** [review]
Looks good!

**Comment by Kreidos** [comment]
> Resolves #1351

You'll wanna edit your main description and put this there. Github doesn't count it in a reply. :)

**Pull request merged**
