### PR TITLE
Bugfix/profile crash #1524

### PR DESCRIPTION
**Pull request by ghost**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

This fix hard-codes mastery rank as 1, and resolves issue with 0x63 status update packet sending incorrect gladiator rank.  As a result, the rank is also set to 0 (Gla).  Several references are added in comments from retail, but appear to have no impact on stability.

Job Info packet has increased in size by two bytes, which has resolved the profile crash, along with the above change.

### CODE REVIEW

**Review by ibm2431 — COMMENTED** [review]
Looks reasonable enough to me; will let Zach have a say on 0x0C in `menu_merit` before hitting any buttons.

**Review by zach2good — APPROVED** [review]
Content seems fine, additional notes and translations are good. I would remove all the debug notes and the things marked as `November client update`, we have the git log and commit messages to let future readers know why it changes.

Similarly, those commits could be squashed together as something like: `Fix Nov 2020 update profile menu crash` etc. 👍

**Comment by zach2good** [comment]
RE the "hacks", I'm fine with that, we don't have that content programmed anyway and there is a note for future readers 👍

**Comment by zach2good** [comment]
`9 commits` 👀

Content looks fine, I'll just squash these 😆

**Pull request merged**
