### PR TITLE
Taisaijin

### PR DESCRIPTION
**Pull request by jarmengaud**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Missing Refresh II drop from Taisaijin.
Note that this would the only way to get this scroll in Topaz, at this time.

### CODE REVIEW

**Comment by ghost** [comment]
Documentation: https://www.ffxiah.com/screenshots/51457.

Looks like it's one or the other.

**Comment by jarmengaud** [comment]
> 
> 
> Documentation: https://www.ffxiah.com/screenshots/51457.
> 
> Looks like it's one or the other.

K, i will try to understand how groups work and fix it :-)

**Comment by jarmengaud** [comment]
Ok i put them in a single group, similar to King Behemoth  Pixie earring/Defending ring

**Review by 59blargedy — APPROVED** [review]
5% seems ok, not a really large sample size on db.

**Review by zach2good — APPROVED** [review]

**Pull request merged**
