### PR TITLE
Bst af3 changes

### PR DESCRIPTION
**Pull request by KnowOne134**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

mobs should pop unclaimed, A bst can charm the 2 other mobs and use them in aid of fight, should despawn after some time if you cant beat the fight

### CODE REVIEW

**Comment by KnowOne134** [comment]
unfortunately looks like mobMod CHARMABLE isnt working

**Comment by Wiggo32** [comment]
```lua
UPDATE `mob_pools` SET `mobType`='16' WHERE `poolid`='3834';
UPDATE `mob_pools` SET `mobType`='16' WHERE `poolid`='4038';
```
This worked for me... see if it helps

**Comment by KnowOne134** [comment]
The reason that works is it removes its NM tag where the mob mod should make it so a mob is charmable when it's set to not be in database

**Comment by ibm2431** [comment]
It's hitting the `MOBTYPE_NOTORIOUS` check for bind and returning before doing anything else.

https://github.com/project-topaz/topaz/blob/master/src/map/utils/battleutils.cpp#L3855-L3860

Might need to rework it to be an `AND NOT` `mobmod_charmable`.

**Comment by KnowOne134** [comment]
charm and gauge now work on NMs that have the lua mobmod.CHARMABLE set

**Pull request merged**
