### PR TITLE
Knights Of Rotund WS for Excalipoor II (20714)

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Now you too can make Light at level one for amazingly gimp damage.

### CODE REVIEW

**Comment by zach2good** [comment]
I might be able to get you the information for excalipoor for the db so this can be an all-in-one PR, please hold for a day or so 👍

**Comment by TeoTwawki** [comment]
Okies

**Comment by zach2good** [comment]
When I added Nihility for reference;
https://github.com/project-topaz/topaz/commit/13984d847277c7dfce6eb45649954bdd000af6bf#diff-1ae46b4dec5f3da0b65d817c19f83b927d563bd5afa95ebc6d6c5f82787fe2eeR10654
```
item_basic:
	(20713, 0, 'excalipoor', 'excalipoor', 1, 30784, 0, 1, 0),
	(20714, 0, 'excalipoor_ii', 'excalipoor_ii', 1, 30784, 0, 1, 0),
item_equipment:
	(20713, 'excalipoor', 1, 0, 4194303, 729, 0, 0, 3, 0),
	(20714, 'excalipoor_ii', 1, 0, 4194303, 729, 0, 0, 3, 0),
item_weapons:
	(20713, 'excalipoor', 3, 0, 0, 0, 0, 2, 1, 240, 1, 0),
	(20714, 'excalipoor_ii', 3, 0, 0, 0, 0, 2, 1, 233, 2, 0),
```

**Comment by TeoTwawki** [comment]
@zach2good so turns out all 6 of those rows already exist with those exact values. I've now added the item mod row, which was all that was left.

I could have sworn I already added all of this back in DSP but when I saw the weaponskill row and script missing thought I must have been mistaken. Its half there half not there, only git blame knows for sure now.

**Pull request merged**
