### PR TITLE
Add Threnody II + add NM Siren's spell list

### PR DESCRIPTION
**Pull request by ibm2431**
Adds the second tier Threnody spells. As these are awarded by gifts, there is no valid method for players to obtain them yet. There also seems to be a client lockout preventing them from appearing if !addallspells is used. However, mobs are capable of using them, including Siren.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Does she actually cast in captures? The other avatars all fake their spells via mobskills. For both player pet and the primes, I believe. If she's actually a for-realz-caster ima custom the heck outa this :smiling_imp:

**Comment by ibm2431** [comment]
In this instance, it's the NM Siren, not the summoned avatar:
siren

**Comment by ibm2431** [comment]
"Hey self, don't you put 'merge ready' labels on stuff you approve?"
"Why yes self, I do. Why do you ask?"
"Do you not approve your own work?"
"Why yes, I do!"

**Comment by zach2good** [comment]
LGTM 👍

**Comment by cocosolos** [comment]
Looks good!

**Pull request merged**
