### PR TITLE
Fix non conforming naming of settings and adjust styling in related scripts

### PR DESCRIPTION
**Pull request by TeoTwawki**
… (mainly wide lines).

Globalize Bomb Coal and Exoray Mold same way Ancient Papyrus is currently done (and npcUtil..)

TODO: Possibly merge FRIGICITE_TIME into OLDSCHOOL_G2 (change from bool to number)?

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [:question:] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Who wants to run through either Crawlers nest or Garliage Citadel on this branch for me so I can legit say it was tested?

**Comment by Kreidos** [comment]
https://github.com/project-topaz/topaz/blob/816dd2eb8e5ed7c043ef130e004b7fe2d77adcb4/scripts/globals/settings.lua#L113-L122

If someone happened to fix **this thing** while in settings.lua they could earn themselves 1 Internet.

**Comment by TeoTwawki** [comment]
@Kreidos I want my 1 internet in unmarked bills.

.. Or the homepoint heal setting gets it see? Nya :gun:

**Comment by zach2good** [comment]
Oh, these cleanups are tasty! I might have some time to test this next week if you don't have time 👍

**Pull request merged**
