### PR TITLE
Inflict new elemental order on Canary

### PR DESCRIPTION
**Pull request by ibm2431**
This branch should live in Canary for _a while_ before going into release.

See #831 for more information, including my previous self-review of the PR.

`fix-elements` branch has been updated to be release-mergable again, including anything referencing elements which I knew was pending back then (open or freshly merged PRs). Hat tip to @Xaver-DaRed for making it so I didn't need to touch synthutils. Don't need to update code referencing elements and weekdays if no such code exists!

I've also browsed through PRs that have landed in release since July looking for things that might reference elements. Most results were resolved during merge conflict resolution, but here's [one perfect example of the power of having your elements be actual elements instead of days of the week](https://github.com/project-topaz/topaz/commit/997e4b6f0366b906f0f9b0692ed04fc3a74dadae).

Not gonna lie: Something is _probably_ broken. I've done my best, but change at this fundamental of a level doesn't come easy. I'll be watching Issue reports.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [ `best of my ability`] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
I had been desperately hoping you would revive this PR, especially because I want it for GEO related shenanigans. I've done a couple of spot-reviews in the past, and one or two now. I'll put this on the top of my review pile so it can get some battle testing in `canary` ⭐

**Comment by ibm2431** [comment]
I was hoping that the addition in #1355 wouldn't trigger a merge conflict, but here we are!

I'll wait for an approval before changing all the commit hashes on you~

**Review by zach2good — APPROVED** [review]
I've done as many spot checks as I can possibly bare, I think the only way to go forward with this is trial by fire in canary for like.. a month

**Comment by zach2good** [comment]
Looks good, fire away!

**Comment by ibm2431** [comment]
Just waiting for the button to turn green!

**Comment by ibm2431** [comment]
Alright canary servers, this is a brutal change. But it must be done to correct tons of things at the fundamental level. 💦 

**If you can think of _anything_ in the game that has anything to do with an element, a day of the week, or weather, you should be sure to test if this merge broke it.**

If you're playing on a canary server, encounter something which you suspect might be because of this merge, and want to open an issue, be sure to specify in the PR that it's canary-post-this and tag me.

**Pull request merged**
