### PR TITLE
Fix Chasing Quotas (DRG AF2) timing

### LINKED ISSUE #413: Quest Chasing Quotas timing not true to current retail.
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When you trade Ceraulian the gold hairpin, you must wait until server midnight to continue the quest.  Current retail requires you to wait just one minute.

`    elseif (csid == 17) then
        player:setCharVar("ChasingQuotas_Progress",1);
        player:setCharVar("ChasingQuotas_date", getMidnight());`

### PR DESCRIPTION
**Pull request by zach2good**
…y one minute (from next midnight)

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

This closes https://github.com/project-topaz/topaz/issues/413

https://www.bg-wiki.com/bg/Chasing_Quotas

### CODE REVIEW

**Review by ibm2431 — APPROVED** [review]
http://forum.square-enix.com/ffxi/threads/46068

>  The conditions for progressing with the following quests have been adjusted.
        Chocobo's Wounds / Chasing Quotas
            Pre-adjustment: 12:00 a.m. (Japan time)
            Post-adjustment: One minute (Earth time)

**Comment by ibm2431** [comment]
I'm holding off on merge due to the char_var name change. I _personally_ feel the chances of a server having a character who triggered the wait but never finished it are very slim, so I'd be willing to merge as-is. But I'll leave this open in case someone wants to make the argument for a migration script.

(We can make sure the var name change is mentioned in whatever @zircon-tpl is planning for the next digest~)

**Comment by zach2good** [comment]
I'm happy to use the old name, it's pretty obvious what it does when you look at it with context and I'd rather not burden operators with a migration for such a little fix.

**Comment by ibm2431** [comment]
That works, thanks Zach!

**Pull request merged**
