### PR TITLE
Bulk remove semicolons from Lua scripts/commands.

### PR DESCRIPTION
**Pull request by mrhappyasthma**
This may not actually be every file, but I did the best I could.

Command applied:
    find . -type f -name "*.lua" | xargs -d '\n' sed -i 's/;//g'

Semicolons are not appropriate in Lua per the style guidelines:
    https://github.com/project-topaz/topaz/blob/master/CONTRIBUTING.md

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by mrhappyasthma** [comment]
There's so many Lua files, I figured we can do it directory by directory. Otherwise it's ridiculous.

(For example: https://github.com/mrhappyasthma/topaz/commit/7277ac15d61230d0093e8cde29057dbefa00bd69)

**Comment by ibm2431** [comment]
And here I was considering doing the same thing and racking up some line diff counts. You beat me to it. 😉

**Comment by KnowOne134** [comment]
That was just commands. Still alot more to do

**Comment by mrhappyasthma** [comment]
Correct. It was too massive of a change to do in a single PR, so there's plenty of room to help out.

I can progressively send out PRs for this but if anyone wants to help out then even better :)

**Pull request merged**
