### PR TITLE
Additional geomancy bubbles

### PR DESCRIPTION
**Pull request by ibm2431**
These are the scripts related to geomancy bubbles as of #494.

I have not reviewed them yet.

As @Omnione won't be the author of this Pull Request - and therefore won't be able to push additional commits - review items will have to be addressed in a future Pull Request.

Please review as if this were a normal Pull Request. We'll compile a list of work items that needs to be done for this branch prior to a merge into canary.

### CODE REVIEW

**Review by cocosolos — APPROVED** [review]

**Comment by ibm2431** [comment]
I have some commits I've been working on for review items I'm wanting changed; so I'll slap a hold on this so people know~

**Comment by ibm2431** [comment]
Update: This will be delayed until after #831 fixes our elemental wheel. Then I'll once again _radically rebase and force push_ this branch.

**Comment by zach2good** [comment]
I've done a medium-strength pass over this, leaving only (and most importantly) `geo.lua` to look over. It mainly needs to conform to the elemental ordering work ibm was doing.

**Review by zach2good — APPROVED** [review]
Dug through `geo.lua` I think this will be fine to be merged into `geo` branch. There is a still a long way to go before any of this ever finds its way to `canary`. I think this will need to be checked against the new elemental ordering things that happened, so all the model/effect/element offsets will need to change.

**Pull request merged**
