### PR TITLE
Fix server crashes during quest "Flyers for Regine"

### LINKED ISSUE #667: Flyers for Regine quest (crash and possible improvements).
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Hello.

Vyvin reported this issue on Discord.

> [...] turning in a flyer to Guilberdrier in Northern San D'Oria for the Fliers for Regine quest crashes my server [...]

I checked on the latest Canary build and compared to this retail video capture of the quest: https://www.youtube.com/watch?v=Se10PQ_nzaY and BGWiki: https://www.bg-wiki.com/bg/Flyers_for_Regine.

~~Trading a Magicmart Flyer indeed crashes topaz_game.exe~~ but I found several possible improvements/differences trying to reproduce this and comparing to the video and Wiki above:

~~When you receive the 15 Magicmart Flyers from Regine (at 1:06 in the video) there should be only one line displayed, obtaining them. On Topaz there's two:
img_20200530_160619~~

Every NPC to which you need to trade a fish should say something when you pass near them ("NPC looks over curisouly for a moment.") at 1:36 (and throughout), on Topaz there's none.

~~There's an extra message displayed when you trade a Magicmart Flyer ("You've handed out X flyer(s)!") on Topaz, shouldn't be there at 3:17 (and throughout).
img_20200529_024101~~

Wasn't able to continue the quest because of said crash above but looks like Vyvin fixed it by doing this:
> [...] I edited his lua script to match Capiria's but with his variables for the FFR quest, Also noticed that Coullene's variable was missing an l in hers
this change stopped the crashing, and allowed me to finish the quest

Thank you!

Edit: mostly fixed by https://github.com/project-topaz/topaz/pull/682! Thank you, @wrenffxi.

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Related to issue #667 

* When receiving multiple stacks of an item -- such as the 15 flyers during this quest -- the player will now only receive one "obtained" mesage for that item.

* Removes the extra message about "You've handed out (x) flyers" from the flyer NPCs, because this message doesn't appear on current retail.

* Fixed some flyer NPCs that were crashing the server when accepting flyers.  Quest can now be completed without issue.

* Fixed some default dialog on a couple flyer NPCs.

*Note: This PR does not add the feature where the player will receive a message when standing close to the correct flyer NPCs.  Therefore, this PR does not entirely address #667*

### CODE REVIEW

**Comment by TeoTwawki** [comment]
```lua
            player:setCharVar("tradeAnswald",0);
            player:setCharVar("tradePrietta",0);
            player:setCharVar("tradeMiene",0);
            player:setCharVar("tradePortaure",0);
            player:setCharVar("tradeAuvare",0);
            player:setCharVar("tradeGuilberdrier",0);
            player:setCharVar("tradeVilion",0);
            player:setCharVar("tradeCapiria",0);
            player:setCharVar("tradeBoncort",0);
            player:setCharVar("tradeCoullene",0);
            player:setCharVar("tradeLeuveret",0);
            player:setCharVar("tradeBlendare",0);
            player:setCharVar("tradeMaugie",0);
            player:setCharVar("tradeAdaunel",0);
            player:setCharVar("tradeRosel",0);
            player:setCharVar("FFR",0);
```
Good lord that is a lot of vars Regine has to zero out. How do you feel about using a mask like stamp hunt and wildcat quests do?

Could also use a single offset to not have to have so many sequential textIDs defined.

> Removes the extra message about "You've handed out (x) flyers" from the flyer NPCs, because this message doesn't appear on current retail.

Trivia: retail removed that when they added the player in range "so and so is interested" thing. I remember the old way of having to just trade macro every NPC till you found them all (or look it up on wiki and not take any breaks mid quest) _cringe_

**Comment by wrenffxi** [comment]
This PR's mainly just to fix the crash.  Can definitely update original issue with additional Nice to Haves for this quest.

I'd be happy to tackle neatening up the code, plus adding the "approach" messages, in a later PR.

**Comment by TeoTwawki** [comment]
Thats a funny way to spell “not it” :D

I kid I kid. Thanks for all you do Wren!

**Review by Wiggo32 — APPROVED** [review]

**Review by ibm2431 — APPROVED** [review]
Thanks, Wren!

**Pull request merged**
