### PR TITLE
Missing Divine_bijou drop in Dynamis Windurst

### PR DESCRIPTION
**Pull request by jarmengaud**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by jarmengaud** [comment]
Aligned boss pop item drop rate to Dynamis San d'Oria

**Comment by kaincenteno** [comment]
Awesome share =)

now that SE released TH percentage drop, all bijous might need a fix too:

It should be 24% for all of them (See http://www.ffxidb.com/search?q=bijou for all bijou with TH0, and https://ffxiclopedia.fandom.com/wiki/Treasure_Hunter for the TH table)

Thoughts?

**Comment by ibm2431** [comment]
Someone remind me what bucket we selected for these boss pop items. Did we go with Common or Very Common? The only non-junk numbers for these are [Loo Hepe](http://www.ffxidb.com/zones/187/loo-hepe-the-eyepiercer) and [Xoo Kaza](http://www.ffxidb.com/zones/187/xoo-kaza-the-solemn), and even then the sample size is low.

Then there's the whole fact that they're rare; which I don't know if ffxidb factors into their sample size calculation.

edit: I've done a bit of Dynamis at TH 8/9, and ~70% drop rate feels higher than I remember. ~50% sounds more accurate to the amount of complaining I've done over not getting pop items to drop.

**Comment by kaincenteno** [comment]
Summoning @TeoTwawki  since he might know more about current percentages in dynamis ^^;;

I am just basing my guess of 24% (VERY COMMON)  for all bijous with the data of all other bijous in FFXIAH.

If the assesement is that they should be COMMON (15%) then should be okay too, but nothing lowered, cuz they are EX-RARE needed to win the boss battle :smile_cat:

**Comment by ibm2431** [comment]
Looking at the TH0 numbers for [Butchnotch's Barbaric Bijou](http://www.ffxidb.com/zones/185/voidstreaker-butchnotch), [Retzpratz's Leering Bijou](http://www.ffxidb.com/zones/134/galkarider-retzpratz), and [Djidzbad's Leering Bijou](http://www.ffxidb.com/zones/134/heavymail-djidzbad), [Fallsplitter's Steelwall Bijou](http://www.ffxidb.com/zones/186/zevho-fallsplitter), and [Andras's Shrouded Bijou](http://www.ffxidb.com/zones/135/marquis-andras) the number seems to be trending towards 24% with "suitable" TH0 sample sizes. TH2 numbers seem to mostly line up as well (some are a little lower than expected rate for Very Common).

These are technically different mobs in different zones, but unless we're willing to entertain the thought that zone boss pops have different drop rates depending on specific mob or zone (which to be honest, I'm not), Very Common would work for all bijou drops.

edit: Except for Jeuno, maybe? The rates for Roving Bijou are trending towards 15% TH0:
- http://www.ffxidb.com/zones/188/morgmox-moldnoggin
- http://www.ffxidb.com/zones/188/sparkspox-sweatbrow
- http://www.ffxidb.com/zones/188/karashix-swollenskull
- http://www.ffxidb.com/zones/188/kikklix-longlegs

**Comment by kaincenteno** [comment]
You are right. I agree, Jeuno Bijou should be COMMON (15%)

**Comment by kaincenteno** [comment]
I'm actually now doubting myself thinking that they should be all COMMON (15%) instead after look at the numbers from Windurst drops. (even if they are really low).

Would love the second opinion from another DEV

**Comment by TeoTwawki** [comment]
> Summoning @TeoTwawki since he might know more about current percentages in dynamis ^^;;

:fire: :fire: :fire: 
***WHO HAS SUMMONED ME?!***
:fire: :fire: :fire: 
###### .
###### .

oh hi. :wave: 

In discussion on discord we couldn't decide for sure if they were "common" or "very common" but consensus was either was fine because it fell between them which we assumed was from reporting skew.

**Comment by jarmengaud** [comment]
so want me to resubmit with 24%?

**Comment by kaincenteno** [comment]
@jarmengaud yes please just change it to 24% and it should be good for now. We can refer to this PR whenever Dynamis is retaken as a project focus.

**Review by 59blargedy — APPROVED** [review]

**Comment by jarmengaud** [comment]
Ok I did some tests and its definitely "very common".
With TH6, Killed 22 NMs and got 16 bijous (so 72%)
Official percent would be 68% vs 50%, so my result is obviously closer to 68%

**Comment by ibm2431** [comment]
@jarmengaud Which zone was this? I'm fine with Very Common for Windurst because it matches the ffxidb numbers from other "three nation" zones. The numbers for Jeuno seem to trend towards Common.

**Comment by TeoTwawki** [comment]
pr deals only with 1 item from one zone.

here are the others


url | zone
------------ | -------------
http://www.ffxidb.com/items/3353 | Dynamis - San D'oria
http://www.ffxidb.com/items/3354 | Dynamis - Bastok
http://www.ffxidb.com/items/3356 | Dynamis - Jeuno
http://www.ffxidb.com/items/3357 | Dynamis - Beaucedine
http://www.ffxidb.com/items/3358 | Dynamis - Xarcabard

**Comment by TeoTwawki** [comment]
Quick reference

url | zone
------------ | -------------
http://www.ffxidb.com/items/3353 | Dynamis - San D'oria
http://www.ffxidb.com/items/3354 | Dynamis - Bastok
http://www.ffxidb.com/items/3355 | Dynamis - Windurst
http://www.ffxidb.com/items/3356 | Dynamis - Jeuno
http://www.ffxidb.com/items/3357 | Dynamis - Beaucedine
http://www.ffxidb.com/items/3358 | Dynamis - Xarcabard

**Comment by wrenffxi** [comment]
Note that, while adding this one missing drop is OK, it's a symptom of a larger issue/TODO.

https://github.com/project-topaz/topaz/issues/311

Droplists in all four cities, beauc, and xarc still need a big overhaul similar to the four Dreamworld zones I've done already.

**Review by cocosolos — APPROVED** [review]

**Comment by jarmengaud** [comment]
The zone i did my tests on was Jeuno.
You can't trust too much ffxidb drop rates for things that are rare. On my tests I of course dropped each bijou before killing any new NM.

**Pull request merged**
