### PR TITLE
Respawn delay for normal mobs

### PR DESCRIPTION
**Pull request by jarmengaud**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Retail respawn delay for normal mobs, Garlaige and Crawlers Nest

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Please cite sources for the new values, thanks. It looks like you gave 5 min across the board for all, and last I knew that was only correct for some outdoor are mobs not all game wide - dungeon mobs in particular were longer. I also know retail had adjusted them more than once.

Just want to see some statement of “I got 300 from xyz”

**Comment by jarmengaud** [comment]
I tested 5 families in each dungeon. They were all 5min. Even mobs that are not part of any GoV page.
I'm pretty sure this was done accross the board for all non-NM mobs, when GoV was introduced.
You want the list of the mobs that I actually tested?

**Comment by kaincenteno** [comment]
> I tested 5 families in each dungeon. They were all 5min. Even mobs that are not part of any GoV page.
> I'm pretty sure this was done accross the board for all non-NM mobs, when GoV was introduced.
> You want the list of the mobs that I actually tested?

I think what Teo needs is the FFXI forum update that mentions this change.

If thats the case then all areas should have 5 min pop, that'd be awesome for leveling up =)

**Comment by jarmengaud** [comment]
damn Kain you realize this change is probably like 6-7 years ago lol

**Comment by jarmengaud** [comment]
Found this old discussion here:
https://forum.square-enix.com/ffxi/archive/index.php/t-10269.html?s=4e177444d020fa7d4d45328406c31160

where the switch from 16 min to 5 min spawn rate is mentioned.
Could not find the official one though

**Comment by TeoTwawki** [comment]
thaannk yooooouuuu :star: 

"I tested personally on retail" or "this webpage -linky-" or "SE says -linky-" just anything so we know where the new data comes from.

**Comment by TeoTwawki** [comment]
p.s. in the future, prolly a good idea to put source right in the commit message, as it stops future editors who aren't in the loop from mistakenly undoing your changes. Teo has been there and (re)done that after ppl thought Teo's change was wrong coz old arse wiki page says this or that.

**Comment by zach2good** [comment]
From that forum post:
> I will say though, the 5 min respawn on mobs was a very welcome adjustment. I find getting coffer keys in these zones is easier now cause the mobs spawn faster.

Seems fair to me 👍

**Review by zach2good — APPROVED** [review]

**Pull request merged**
