### PR TITLE
[WIP] Setzor's fishing

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**This is meant for testing purposes only. It is not ready for use. Any server using this code does it at it's own risk.**

Setzor's fishing code, posted in FfxiPrivateServers Discord, adapted for Topaz and with the compile errors solved.
The code needs to be cleaned, but for now it does function.

- Skill ups work
- Zones up to Treasures of Aht Uhrgan have their pools with their fish and items and the correct info. Mostly.

*Disclaimer*
I did get Setzor's permission to PR his code to Topaz, originaly for DSP., so long as proper credit was given.
This was originaly coded by Setzor and used/tested in Eden server by it's players for a year.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

*Related Issues*
#763 #168

### CODE REVIEW

**Comment by Noikar** [comment]
Dawnbreak is willing to test this as long as @Xaver-DaRed can confirm it's complete enough to run on a server.

**Comment by Kreidos** [comment]
@Lynnea1320 I'm not sure anyone can confirm that at this point, it's still WIP and if it were ready then this could be marked as non-draft. :)

Thanks for this though, both to Setzor originally and to Xaver for integrating! Look forward to taking a closer dive when I have time.

**Comment by Noikar** [comment]
Xaver DMed me and said it's ready to be tested for the most part, so I
merged it and he's on our server keeping an eye on issues that may arise.

**Comment by Xaver-DaRed** [comment]
the act of fishing and any of its possible outcomes dont seem to make anything explode.
regarding other fishing related activities, i dont think the fishing guild is ready. havent tested that far yet

**Comment by ibm2431** [comment]
Can remove the 2010-2015 DSP copyright from the _new_ source files too, as Setzor has sole copyright on the files (until we modify it). GPL3 boilerplate should remain.

**Comment by Arklus** [comment]
Why wont this compile with linux

**Comment by Kreidos** [comment]
You'll have to be more specific, @Arklus. It seems to compile just fine on both my systems. (Debian 10 GCC 8.3 / Debian 9 GCC 7.4)

**Comment by Arklus** [comment]
Clearly this thing isnt completely not working on my server it crashes my client when fishing . and my rod was missing

**Comment by Xaver-DaRed** [comment]
As discussed in discord, whatever issue you had doesnt have to do with this code concretely. Lockstyle mechanics need to be revised though.

Also, to all the ppl pulling this PR, it would be helpfull if you provided feedback on it, so we can get this fixed, cleaned and ready.

**Comment by Xaver-DaRed** [comment]
Setzor donated an updated version of his fishing system, making this one obsolete.
I will PR it soon, once its ready.
Im closing this PR in the meantime.

**Pull request closed without merging**
