### PR TITLE
Update beast_roll.lua

### PR DESCRIPTION
**Pull request by Acrossy**
Hello, since I am new to github I hope I am not doing anything wrong.
I am trying to send a proposal for BST roll to actually add ranged atk to pets.
I added the lines that should provide the effect, I hope.
Please check if it's in accordance.
Thank you.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by neuromancerxi** [comment]
BG Wiki confirms RATTP as well as ATTP: https://www.bg-wiki.com/bg/Beast%20Roll

> This roll also increases pet ranged attack.

**Comment by Acrossy** [comment]
> 
> 
> BG Wiki confirms RATTP as well as ATTP: https://www.bg-wiki.com/bg/Beast%20Roll
> 
> > This roll also increases pet ranged attack.

Thank you for referencing that. I completely forgot to put the reference and link to a source! 
/bow

**Comment by zach2good** [comment]
Hi! Welcome to the project and congrats on your first PR! These changes are very simple and obviously backed up by the wiki entry, so (in this case) there's no need to test them :)

But, we do require contributors to "sign" our _Limited Contributor License Agreement_ by putting an 'x' in the boxes that were pre-filled in the PR description like so:
```
I affirm:

[x] that I agree to Project Topaz's Limited Contributor License Agreement, as written on this date
[x] that I've tested my code since the last commit in the PR, and will test after any later commits
```

If you could edit the description with those 'x' marks we can get this merged :)

Thanks again!

**Comment by Acrossy** [comment]
> 
> 
> Hi! Welcome to the project and congrats on your first PR! These changes are very simple and obviously backed up by the wiki entry, so (in this case) there's no need to test them :)
> 
> But, we do require contributors to "sign" our _Limited Contributor License Agreement_ by putting an 'x' in the boxes that were pre-filled in the PR description like so:
> 
> ```
> I affirm:
> 
> [x] that I agree to Project Topaz's Limited Contributor License Agreement, as written on this date
> [x] that I've tested my code since the last commit in the PR, and will test after any later commits
> ```
> 
> If you could edit the description with those 'x' marks we can get this merged :)
> 
> Thanks again!

Yeah I noticed it was just a copy paste issue basically! After a friend of mine pointed to me that the fix was something so simple, I noticed from the Chaos Roll lines what I needed to do, so I just copied the lines on beast_roll but added RATTP over instead!
I am hardly a coder, AT ALL, so when I noticed it was something so simple to edit I just had to give it a try.
Also regarding the commitment statements I just edited it! Both marks are checked! 
Once again tyvm :)

**Pull request merged**
