### PR TITLE
Passing party leader dismisses Trusts

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

EDIT: Tested, works as expected

### CODE REVIEW

**Review by Kreidos — APPROVED** [review]
Really?? I'd no idea. :shrug:

**Comment by TeoTwawki** [comment]
huh. didn't know you _could_ pass lead with them out.

**Comment by zach2good** [comment]
Will need to check in retail

**Comment by zach2good** [comment]
Tested on retail, this works fine. Trust disappear without an animation, but that's fixed in this branch: https://github.com/project-topaz/topaz/pull/1424

**Pull request merged**
