### PR TITLE
Add RoE headers to VC filter for Windowsers

### PR DESCRIPTION
**Pull request by Kreidos**
:crossed_fingers: I hope!

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I can't _test my code_ since the last commit.

### CODE REVIEW

**Comment by zach2good** [comment]
Will boot up and check tomorrow, but looks sane at a glance, thanks!

**Comment by zach2good** [comment]
Ah, you also need entries for your `Source Files`

**Comment by zach2good** [comment]
I've tried to make this work nicely... but it jus _wont_. It breaks all the other filters and doesn't produce any errors...

So I'd say just hold on until I can finish the transition to CMake and then you won't have to worry about it 🤷

**Comment by TeoTwawki** [comment]
whaaaaaaaaaaat?

I'll take a look tonight. this normally isn't difficult.

**Pull request closed without merging**
