### PR TITLE
Mazurka Fix

### PR DESCRIPTION
**Pull request by Omnione**
• Added the ability to cast mazurka in appropriate zones.
• Added effect flags to wear on action against mob and wear on mob hit.

This fixes issue #528

BRD Mazurka should be allowed in dungeons (and removal on hit or attack)
issued by @kaincenteno

**_I affirm:_**
- [X] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [X] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by kaincenteno** [comment]
Brilliant @Omnione  thank you :D

**Comment by ibm2431** [comment]
All the additions check out, but I'm curious, where does the list of allowed zones come from? For example, I'm seeing that Newton Movapolis and Alzadaal Undersea Ruins are getting the flag, but Oldton Movapolis and Salvage zones aren't

**Comment by Omnione** [comment]
Well for starters i did not touch any SOA area's due to them not even been touched properly yet,
As for Oldton Movapolis, i must have missed that one, my bad, i wasn't too sure on salvage, i need more info to be confident on adding them, but the rest is from research and logic, i.e. if a zone leads to a bcnm you cannot use Mazurka, stuff like this is really hard to find info on, alot was from memory, i went to every zone in the game and assesed it, and made a judgment, while i cannot 100% say for certain these are correct, i feel they are right given the what each zone i added did not give me any reason to not allow Mazurka.

**Comment by Omnione** [comment]
right gonna push Oldton

**Comment by ibm2431** [comment]
That works for me! I don't see any additions that I think would be _wrong_ - was just wondering if a site had a chart I didn't know about.

**Comment by kain** [comment]
Guys, can you, please, not tag me? Use @kaincenteno not @kain

**Comment by Omnione** [comment]
I wish, this was hard to do, took all day to go through every zone and asses it, i looked everywhere.

**Comment by Omnione** [comment]
Oh sorry kain, you are right i used the discord tag, so sorry

**Comment by kain** [comment]
No problems! Thank you!

**Review by ibm2431 — APPROVED** [review]

**Comment by kaincenteno** [comment]
@UynGH can you check if mazurka is allowed inside bcnm areas? if u check 3 random bcnm areas and it works then most likely this restriction has been lifted

**Comment by 59blargedy** [comment]
@kaincenteno do you mean inside a battlefield or just in the general zones like balga's dias, boneyard gully, etc?
can tag @project-topaz/researcher and i'll see it too, Nyu pointed me here to help :)

**Comment by 59blargedy** [comment]
tested boneyard gully (in bcnm and out), jade sepulcher (same) and qu'bia arena inside bcnm, mazurka can be cast.

**Comment by Omnione** [comment]
Thanks guys, ill update soon

**Comment by TeoTwawki** [comment]
Is it  unblocked everywhere now? Maybe can do away with its zone flag altogether?

**Comment by Omnione** [comment]
I dont belive its everywhere but it like 90% of zones, just not places like moghouse, colosseum, and stuff like that.

**Pull request merged**
