### PR TITLE
Insert spaces between commas inside scripts

### PR DESCRIPTION
**Pull request by ibm2431**
I'm sorry. I don't know what's come over me today.

Only commit is just this:
give-me-space

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by kaincenteno** [comment]
love this <3 i always hated seeing everything together. Is there any check on github to prevent this on future PRs? :smile:

**Comment by ibm2431** [comment]
Not trying to sneak anything in, I promise:
whitespace-only

**Comment by ibm2431** [comment]
@kaincenteno We'll have to look into an automatic linter of some kind. At the moment we're just doing manual checks.

**Review by cocosolos — APPROVED** [review]

**Review by TeoTwawki — APPROVED** [review]

**Comment by ibm2431** [comment]
Travis says it's good, and it's whitespace only; not waiting on appveyor~!

(Travis is the one that checks Lua on top of the Linux build, AppVeyor doesn't)

**Pull request merged**
