### PR TITLE
Adds mixin for eruca crawlers sleeping habits and regain mod

### LINKED ISSUE #1069: Eruca Crawlers should sleep during the night, and regain TP during firesday
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

From [wikipedia](https://ffxiclopedia.fandom.com/wiki/Category:Crawlers):
"Eruca, with red and black coloring can be found in certain regions on the Aradjiah continent, these Crawlers have special attributes not native to standard Crawlers. They sleep during the night and also regain TP during Firesday."

Thanks to Daemun@GoldSaucer for reporting.

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #1069 

Thanks to Teo and especially Wren for his urganite mixin work which I used as the skeleton for this mixin.

The regain portion was actually untested because I didn't fancy waiting around for firesday.  The regain amount is a complete guess too.  This might vary from crawler to crawler and the mixin might need another variable for it.

### CODE REVIEW

**Comment by tankfest** [comment]
Also had to add the NO_LINK mob mod to this PR to disable linking temporarily for the crawlers while asleep.

**Comment by tankfest** [comment]
Last order of business to make this behavior 100% is to determine what the eruca crawlers do when it's sleepy time and they have been pulled to the zone or something.  Right now, they will just fall asleep immediately wherever it was they disengaged and stay there until sun up or re-engage, but they should likely head to their respawn point before sleepy time.

If someone wants to recommend a fix for that I'll include it, otherwise it's good to go as is imo.

**Comment by ghost** [comment]
From Discord (thanks to Apo for checking on retail!):
> if you move them even a couple yalms outside of their spawn point, they despawn and respawn already asleep
if you leave them at their spawn point, logout, come back in without aggroing them, they go back to sleep after exactly 2 mins
until that 2 mins is reached, they wander around their spawn like normal

**Comment by tankfest** [comment]
Waiting on teo's distance function PR so that we can get easy distance from home determination for the crawlers.

**Comment by tankfest** [comment]
It's finished!  Tested with teo's checkDistance fixes as well.

Eruca crawlers will now behave in a retail-like manner when a player disengages them during sleep hours:  

- For servers that allow mobs to roam home if disengaged, the crawlers will roam like normal mobs until they are within 25y of their spawn, at which point a 2 minute timer will put them to sleep again if they remain undisturbed, and it's still night time.
- For servers that despawn mobs that roam too far from spawn, they will depop like normal, and spawn asleep if it's still night.
- For either server, if the crawler is disengaged within 25y of its spawn position, it will idle for 2 minutes and then sleep, if it's still night.

Thanks for testing this on retail ^.^

**Pull request merged**
