### PR TITLE
[version update] 30200304_3

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by ibm2431 — APPROVED** [review]
Thanks as always, Wren! 👍 

Feel like updating `zone_settings` while you're here?

**Comment by wrenffxi** [comment]
I don't know where the values come from, for entries into zone_settings and zone_weather.

**Comment by TeoTwawki** [comment]
> Thanks as always, Wren! 
> 
> Feel like updating `zone_settings` while you're here?

I didn't add the flags or music values (presumably same as other WoE zones) but I did change the names and give them the default port in another PR just now

**Comment by ibm2431** [comment]
That works for me, thanks guys!

**Pull request merged**
