### PR TITLE
Implement Eco-Warrior quests

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [ ] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

This branch will implement the two missing Eco-Warrior quests, and refurbish Eco-Warrior Windurst.

Currently Eco-Warrior Windurst has a few bugs and incorrect dialogue/options, commit 6b5d0e6 fixes those and cleans the scripts/variables.

This is a new PR for #743 so that requested changes could be made.

### CODE REVIEW

**Review by Wiggo32 — APPROVED** [review]
I'm not familiar with how these work on retail, however these are lua scripts and only affect the mobs/npcs associated with the quest so no real chance of breaking much of anything and I trust the author has scripted events to behave accordingly with the best of their ability. I see no reason not to approve and if tweaking is needed later due to new research, that can always be added.

**Comment by TeoTwawki** [comment]
@tankfest for future reference, you can use force push to overwrite existing PR's with new content so that you don't need to create new ones. this keeps the comment history intact while making the content match your current work.

**Review by TeoTwawki — APPROVED** [review]
Looks good enough to me. additional features need added to make this 100%.

The previous PR for these had non retail behavior (needed more than tweaking) but this one doesn't. I will open an issue for the missing feature.

**Comment by TeoTwawki** [comment]
#924 as promised

**Pull request merged**
