### PR TITLE
Adjust Trust and Mount flags in Adoulin and ToAU zones

### PR DESCRIPTION
**Pull request by jarmengaud**
Missing mount flag in some Adoulin open fields
Removed mount flag in Adoulin dungeons
Adding trust flag in ToAU event zones

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by kaincenteno** [comment]
ouch wasn't aware that people were able to use mounts in dungeons lol. Glad this fixed it

**Comment by ibm2431** [comment]
May wanna go over these again; SOA dungeons are losing Escape and Fellow.

Mazurka might be okay; [Omni deliberately didn't touch SOA zones when he was adjusting Mazurka flags last](https://github.com/project-topaz/topaz/pull/539).

flags

**Comment by jarmengaud** [comment]
Escape is intended, release branch does not have it either, because it takes more work to allow escape (need to define escape zones).
I will add back fellow

**Comment by jarmengaud** [comment]
did a quick test on retail, you can use mazurka in SOA dungeons

**Comment by jarmengaud** [comment]
Ok flag FELLOW added for dungeons, even though this flag is not consistent across all zones, which has never been detected as an issue since... fellow is not implemented :-)

**Pull request merged**
