### PR TITLE
Straighten Moogles away from their lives of crime

### PR DESCRIPTION
**Pull request by ibm2431**
I know Moogles need to make a living, but trafficking in duplicates of adventurers' swimsuits is not the way!

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by zach2good — APPROVED** [review]
They must repent!

image

**Comment by ibm2431** [comment]
More descriptive description: Porter Moogles use their own special trade function which wasn't hit in #1196

**Comment by zach2good** [comment]
The problem with patching holes like this is that, since our systems are so _jank_, cases like this are bound to pop up. I'm not looking forward to these sorts of shenanigans when I roll out packetguard...

**Comment by drlongnecker** [comment]
Thanks for the quick help on this! =]

**Comment by ibm2431** [comment]
Teamwork makes the dream work!

**Pull request merged**
