### PR TITLE
Update abilities.sql

### PR DESCRIPTION
**Pull request by illzbee**
added 295,'curing_waltz_v'

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by cocosolos** [comment]
Looks good, is there a reason you moved this out of order? It looked like you had it in the right place in the first commit.

**Comment by TeoTwawki** [comment]
looks like travis was having a partial outage at the time of the 1st commit, guessing you mistakenly thought you needed to put new stuff at the bottom because of that error. the rows should stay sorted by primary key and the error was just the service being partly out.
> apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install software-properties-common g++-7 luajit-5.1-dev libzmq3-dev mysql-client-core-5.6 mysql-server-5.6 mysql-client-5.6 luarocks python3.7" failed and exited with 100 during .

**Comment by TeoTwawki** [comment]
p.s. commit messages should be more descriptive than "update thing"

**Comment by illzbee** [comment]
When I went on my test files it moved it on the bottom. Which made me think
that was the cause of the error. I won't make the mistake again. Thanks for
letting me know.

**Review by Wiggo32 — APPROVED** [review]

**Review by Wiggo32 — COMMENTED** [review]
We wanted to put it back in order though right?

**Pull request merged**
