### PR TITLE
Fixed some of the map quests

### PR DESCRIPTION
**Pull request by Noikar**
**_I affirm:_**
- [X] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [X] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Some weren't giving proper rewards or key item notifications. Will push more as we find them.

### CODE REVIEW

**Comment by kaincenteno** [comment]
Does this need to be rebased? I see lots of changes not related to map quests  :crying_cat_face:

**Comment by Kreidos** [comment]
Indeed, seems extra commits, as well as map.conf may have been accidentally added. :(

**Comment by Noikar** [comment]
Ugh I thought I slapped a clean Topaz over it but maybe I messed it up like
I usually do.

**Comment by Noikar** [comment]
I thought I did it with the Release Branch checked out so idk what happened but I'll try it again lol thanks for the heads up.

**Comment by TeoTwawki** [comment]
if you clone a clean topaz locally, you can force push to arbitrary urls and specify what branch. if you force push over the branch on your fork the PR comes from, it will automatically replace the PR content and let you pretend nothing wrong ever happened. I haven't at all done this to hide hundreds of mistake on my part. Or if I didn't you can't prove nuthin! :wink:

**Pull request closed without merging**
