### PR TITLE
Fix regression from bostaunieux PR

### PR DESCRIPTION
**Pull request by jarmengaud**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fix an incorrect merge conflict resolution (new poolid for Garms)

### CODE REVIEW

**Comment by kaincenteno** [comment]
new poolid? oh great this will break atori again cuz that's another poolID xD

**Review by 59blargedy — APPROVED** [review]

**Comment by ibm2431** [comment]
When will the other regressions be addressed?

**Comment by jarmengaud** [comment]
Unless i missed something, that's the only regression that was discussed in the previous PR, no?

**Comment by cocosolos** [comment]
conflict
https://github.com/project-topaz/topaz/compare/2b9832f35992a00e21b93a10b84c133d426dbc48...8d2290f928b7612d9bc62cc5b14da519d5ae208c

**Pull request merged**
