### PR TITLE
This *should* fix Guivre's ability to walk around

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits ~~(need a volunteer to test, as I lack time - but I have other mobs using this same code with diff pos's working fine!)~~ tested by Zach

thought: should onPath be a local function?

### CODE REVIEW

**Comment by kaincenteno** [comment]
ouch that's a huge array, i take npc path is still borken

**Comment by TeoTwawki** [comment]
> ouch that's a huge array, i take npc path is still borken

yeah I seriously dislike the way these are handled but doubly so when there are so freakin many points in the array. I probably should have rounded these to nearest rather than truncating as well, but I want to know if he even moves now before messing with that more.

**Comment by zach2good** [comment]
Confirmed, he wanders around as he should 👍

**Comment by ibm2431** [comment]
Culled some intermediate points where only one axis was being changed
[culled.txt](https://github.com/project-topaz/topaz/files/4383940/culled.txt)

**Review by ibm2431 — APPROVED** [review]

**Pull request merged**
