### PR TITLE
Adds Tachi/+1 and Raptor Strap/+1 desynths

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Thanks to Nireya@GoldSaucer for reporting these.

### CODE REVIEW

**Comment by m241dan** [comment]
Only concern is that https://ffxiclopedia.fandom.com/wiki/Tachi claims its lv31 for the Tachi desynth (though 33 for the craft). Bg-wiki doesn't specify.

**Comment by tankfest** [comment]
I saw that claim, both in ffxiah's message board and bgwiki.... but are we to believe a level 33 synth has a level 31 desynth?  what madness is this?

**Review by 59blargedy — APPROVED** [review]

**Comment by m241dan** [comment]
> I saw that claim, both in ffxiah's message board and bgwiki.... but are we to believe a level 33 synth has a level 31 desynth? what madness is this?

The most maddening madness, we should probably pick one and leave a comment in the code saying "we saw this, but this is what we chose"

**Comment by TeoTwawki** [comment]
> leave a comment

this here? that is how you keep people from fixing your fix for the fix that they fixed that you fixed... something something Halver

**Review by Wiggo32 — APPROVED** [review]

**Pull request merged**
