### PR TITLE
Minor settings.lua update.

### PR DESCRIPTION
**Pull request by ghost**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Hello.

Enabled all expansions by default and turned the CoP areas level cap off to be retail accurate.

Thanks!

### CODE REVIEW

**Review by ibm2431 — APPROVED** [review]
Just because the missions aren't finished doesn't mean we should lock what is.

**Review by Kreidos — APPROVED** [review]
I agree. Everything should probably be unlocked by default.

**Comment by kaincenteno** [comment]
can the crafting be increase to the previous default (2.6) as it's difficult to skill up with 1.0? 

I'm not sure if Weapon skill skillup also needs to be reverted back to its previous default (2.5)

I know we are targetting current retail, but with the current settings for skill ups becomes impossible ^^;; (unsure about weaponskill though but for sure for crafting)

**Comment by TeoTwawki** [comment]
> can the crafting be increase to the previous default (2.6) as it's difficult to skill up with 1.0?
> 
> I'm not sure if Weapon skill skillup also needs to be reverted back to its previous default (2.5)
> 
> I know we are targetting current retail, but with the current settings for skill ups becomes impossible ^^;; (unsure about weaponskill though but for sure for crafting)

how about we fix the crafting to be retail accurate at 1.0 instead. 1.0 is ***supposed to be*** retail, and moving it back to 2.6  just hides the underlying problem. Like being told to clean your room and shoving everything under the bed before mom & dad come back. Nearly every server customizes this  - just change yours.

**Comment by kaincenteno** [comment]
stop looking under my bed @TeoTwawki  :panda_face:

**Comment by TeoTwawki** [comment]
@kain the monster that lives there is complaining, says to get a storage locker instead of using his home for all your stuff.

**Comment by Kreidos** [comment]
If we want 1.0 to be retail, we should in fact change the defaults in map.cpp to 1.0 as well; looks like whoever changed it in the default conf missed changing it there.

**Comment by TeoTwawki** [comment]
> If we want 1.0 to be retail, we should in fact change the defaults in map.cpp to 1.0 as well; looks like whoever changed it in the default conf missed changing it there.

<.<  
\>.>  
~~You can't prove nothin~~ _git log rats Teo out_
You'll neva take me alive coppa!
:running_man: :cloud: :cloud: :cloud: 

.  
.  
.  
The synth utils does need at least a partial rewrite though. Has for some time.

**Review by ibm2431 — COMMENTED** [review]
While you're here, Nyu:
`USE_ADOULIN_WEAPON_SKILL_CHANGES` is currently defaulting to false

**Pull request merged**
